import streamlit as st
from utils.data_loader import get_all_employee_ids, get_employee_by_id
from utils.prediction import predict_employee_attrition
from utils.recommendation import generate_retention_recommendations
from utils.pdf_report import generate_pdf_report

def render_hr_reports():
    st.markdown("""
        <div style="margin-bottom: 1.5rem;">
            <h2 style="color: #1e3a8a; margin: 0;">📄 HR Executive Reporting Center</h2>
            <p style="color: #64748b; margin: 0.2rem 0 0 0;">Generate, preview, and download formal PDF dossiers for executive leadership</p>
        </div>
    """, unsafe_allow_html=True)
    
    all_emp_ids = get_all_employee_ids()
    
    col1, col2 = st.columns([1, 2])
    with col1:
        st.markdown("### 🎯 Single-Employee Dossier")
        selected_id = st.selectbox("Select Employee for Report Generation:", options=all_emp_ids, index=0)
        
        emp_record = get_employee_by_id(selected_id)
        if emp_record:
            st.write(f"**Role:** {emp_record.get('JobRole')}")
            st.write(f"**Department:** {emp_record.get('Department')}")
            st.write(f"**Tenure:** {emp_record.get('YearsAtCompany')} years")
            
            with st.spinner("Generating official PDF dossier..."):
                pred = predict_employee_attrition(emp_record)
                recs = generate_retention_recommendations(emp_record, pred["risk_factors"])
                pdf_bytes = generate_pdf_report(emp_record, pred, recs)
                
            st.download_button(
                label=f"⬇️ Download Employee #{selected_id} PDF Dossier",
                data=pdf_bytes,
                file_name=f"Executive_Report_Employee_{selected_id}.pdf",
                mime="application/pdf",
                type="primary",
                use_container_width=True
            )

    with col2:
        st.markdown("### 📋 PDF Report Inclusions & Standards")
        st.markdown("""
            Each formal PDF report generated by AttritionSense AI conforms to enterprise documentation standards:
            
            - **Executive Risk Tier:** Standardized color-coded indicator (High / Medium / Low).
            - **Verified HR Attributes:** Demographic, tenure, compensation, and satisfaction records.
            - **Attributed Risk Drivers:** Concrete factors explaining the machine learning prediction score.
            - **Prescriptive Action Plan:** Ranked, prioritized retention initiatives with designated owners.
            - **Audit & Sign-Off Section:** Formal governance block for HR business partner signatures and case reviews.
        """)
        
        st.info("💡 **Compliance Notice:** Reports are encrypted in transit and intended strictly for authorized HR Talent Partners and People Leadership.")
